[build]
  base = "/"
  public = "./public"
  functions = "./functions/"
  command = ""

[dev]
  prebuild = ""
  port = 3000 # Port that the dev server will be listening on
  functionsPort = 34567 # port for functions server
  publish = "./public" # If you use a _redirect file, provide the path to your static content folder
  #command = "cd ./functions && npm i"
  #command = "node ./scripts/dev.js"

[context.dev.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
